### ISSUE TITLE
Internal Error..

### ISSUE THREAD

**Issue by ramstein74** [mjbeller/web2py-starter#2]
I just cloned your app to my applications folder as "fileit" and my web2py is 2.14.3
![image](https://cloud.githubusercontent.com/assets/1210858/14458964/01a69438-00ad-11e6-83e8-d96dabf8610f.png)

can you help ?

**Comment by ramstein74** [comment]
pydal i guess...

**Comment by mjbeller** [comment]
What was the problem?

**Comment by ramstein74** [comment]
dont know but i looked at the web2py console and was there something about
pydal.
I had it installed but reinstalled it again via pip and dont now it that
solved it but when i  refresh the page , problem gone!
thank u

https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
Sem
vírus. www.avast.com
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-04-12 15:49 GMT+01:00 Michael Beller notifications@github.com:
