### ISSUE TITLE
Too much bandwidth ?

### ISSUE THREAD

**Issue by ramstein74** [mjbeller/web2py-starter#3]
Hello im using this starter for my app
I noticed that only traffic from my pc to the server fills a daily bandwidth between 200Mb and 300Mb
Its huge!!!
How can i reduce it ?

Regards

**Comment by mjbeller** [comment]
I have not experienced that bandwidth usage.  Can you isolate the specific large files transferred between the browser and server?

**Comment by ramstein74** [comment]
The biggest one is jquery-ui.min.js around 240kb
For every 5 clicks i download 1MB...
i´m using now the cdn version... to cache and spare webfaction usage


2017-06-26 6:01 GMT+01:00 Michael Beller <notifications@github.com>:

**Comment by mjbeller** [comment]
The CDN versions will certainly be better - I'll change that in the future
